Asintel 599 dashboard pipelines
SkillsFundingAgency/das-data-factory pull request #26
Opened 2020-08-17 11:29 UTC by sarmaevanidfe

Please peer review azure data factory pipeline to generate key

2020-08-20 07:01 UTC, arvinthseran approved these changes

2020-08-24 13:53 UTC, arvinthseran approved these changes

2020-08-27 11:31 UTC, uhimabindu requested changes
Please Change GetRunId TimeOut to 30 mins.
Also, Please take the latest changes from Master.

2020-08-27 11:45 UTC, uhimabindu reviewed
Trigger Name is called - Trigger-GenerateKy - An E is missing in the name. Is that intentional?

2020-08-27 14:24 UTC, closed without merging