Asintel 756 import emp acc fin comt data
SkillsFundingAgency/das-data-factory pull request #37
Opened 2020-09-30 09:07 UTC by sarmaevanidfe

2020-10-01 08:53 UTC, uhimabindu requested changes
Please change "secureInput": false to True . Found 4 where it is false.

2020-10-01 09:01 UTC, arvinthseran commented on pipeline/ImportEmpAccFinComtToDataMart.json
> +					"secureInput": false
secureOutput should be true?

2020-10-01 09:02 UTC, arvinthseran commented on pipeline/ImportEmpAccFinComtToDataMart.json
> +								"secureInput": false
can secureOutput and secureInput be false?

2020-10-01 09:02 UTC, arvinthseran commented on pipeline/ImportEmpAccFinComtToDataMart.json
> +								"secureInput": false
can secureOutput and secureInput be false?

2020-10-01 09:05 UTC, arvinthseran reviewed
I can see in couple of places that secureOutput and secureInput is set as false, please have a look

2020-10-01 13:12 UTC, arvinthseran approved these changes

2020-10-01 13:12 UTC, arvinthseran commented on pipeline/Master-ImportAccUsersComtFinResvToDataMart.json
> +				"name": "ExecuteImportComtTpDM",
ExecuteImportComtToDM?

2020-10-01 13:20 UTC, uhimabindu requested changes
I see this dataset/SrcAccountsDB.json and there is already dataset/SrcAccounts.json that should have been used.

Please also rename DataSets by removing the suffix Db to be consistent with what we have already.

2020-10-05 09:17 UTC, uhimabindu approved these changes
Approved

2020-10-05 09:19 UTC, merged