Asintel 1411 employer feedback
SkillsFundingAgency/das-data-factory pull request #81
Opened 2021-04-01 10:08 UTC by sarmaevanidfe

2021-04-01 14:31 UTC, uhimabindu requested changes

2021-04-01 14:31 UTC, uhimabindu commented on pipeline/ImportPFBEToDataMart.json
> +									"name": "ProviderName"
name here is a Feedback Name and not Provider Name.

2021-04-01 16:21 UTC, uhimabindu approved these changes

2021-04-06 10:21 UTC, arvinthseran approved these changes

2021-04-06 10:52 UTC, merged